<a href="https://colab.research.google.com/github/meriemdouider1/data_mining_project/blob/main/data_final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [63]:
import pandas as pd

## DÃ©mographique_data

In [64]:
data_1 = '/content/DEMO_J.xlsx'
d1= pd.read_excel(data_1,
sheet_name=0,
header=0,
index_col=False,
keep_default_na=True
)
len(d1)

9254

In [65]:
d1.head()

    SEQN  SDDSRVYR  RIDSTATR  RIAGENDR  ...  SDMVSTRA  INDHHIN2  INDFMIN2  INDFMPIR
0  93703        10         2         2  ...       145      15.0      15.0      5.00
1  93704        10         2         1  ...       143      15.0      15.0      5.00
2  93705        10         2         2  ...       145       3.0       3.0      0.82
3  93706        10         2         1  ...       134       NaN       NaN       NaN
4  93707        10         2         1  ...       138      10.0      10.0      1.88

[5 rows x 46 columns]

##Eximanation_Data

In [66]:
data_2 = '/content/Examination_Data.xlsx'
d2= pd.read_excel(data_2,
sheet_name=0,
header=0,
index_col=False,
keep_default_na=True
)
len(d2)

8704

In [67]:
d2.head()

   Unnamed: 0   SEQN  BMDSTATS  BMXWT  ...  OHAROCDE  OHARNF  OHAROTH  OHAPOS
0           0  93703         1   13.7  ...       NaN     1.0      NaN     1.0
1           1  93704         1   13.9  ...       NaN     1.0      NaN     1.0
2           2  93705         1   79.5  ...       NaN     1.0      NaN     1.0
3           3  93706         1   66.3  ...       NaN     1.0      NaN     1.0
4           4  93707         1   45.4  ...       NaN     1.0      NaN     1.0

[5 rows x 368 columns]

In [68]:
dd1=pd.merge(d1,d2,how='outer')

In [69]:
len(dd1)

9254

In [70]:
dd1.head()

    SEQN  SDDSRVYR  RIDSTATR  RIAGENDR  ...  OHAROCDE  OHARNF  OHAROTH  OHAPOS
0  93703        10         2         2  ...       NaN     1.0      NaN     1.0
1  93704        10         2         1  ...       NaN     1.0      NaN     1.0
2  93705        10         2         2  ...       NaN     1.0      NaN     1.0
3  93706        10         2         1  ...       NaN     1.0      NaN     1.0
4  93707        10         2         1  ...       NaN     1.0      NaN     1.0

[5 rows x 413 columns]

##Laboratory_data

In [71]:
data_3 = '/content/Laboratory_Data_2017_2018(2).xlsx'
d3= pd.read_excel(data_3,
sheet_name=0,
header=0,
index_col=False,
keep_default_na=True
)
len(d3)

7936

In [72]:
dd2=pd.merge(dd1,d3,how='outer')

In [73]:
len(dd2)

17190

In [74]:
dd2.head()

    SEQN  SDDSRVYR  RIDSTATR  RIAGENDR  ...  LBXHBC  LBDHBG  LBDHD  LBXHBS
0  93703      10.0       2.0       2.0  ...     NaN     NaN    NaN     NaN
1  93704      10.0       2.0       1.0  ...     NaN     NaN    NaN     NaN
2  93705      10.0       2.0       2.0  ...     NaN     NaN    NaN     NaN
3  93706      10.0       2.0       1.0  ...     NaN     NaN    NaN     NaN
4  93707      10.0       2.0       1.0  ...     NaN     NaN    NaN     NaN

[5 rows x 549 columns]

##Questionnaire_data

In [75]:
data_4 = '/content/DIQ_J.xlsx'
d4= pd.read_excel(data_4,
sheet_name=0,
header=0,
index_col=False,
keep_default_na=True
)
len(d4)

8897

In [76]:
dd3=pd.merge(dd2,d1,how='outer')

In [77]:
len(dd3)

17190

In [78]:
dd3.head()

    SEQN  SDDSRVYR  RIDSTATR  RIAGENDR  ...  LBXHBC  LBDHBG  LBDHD  LBXHBS
0  93703      10.0       2.0       2.0  ...     NaN     NaN    NaN     NaN
1  93704      10.0       2.0       1.0  ...     NaN     NaN    NaN     NaN
2  93705      10.0       2.0       2.0  ...     NaN     NaN    NaN     NaN
3  93706      10.0       2.0       1.0  ...     NaN     NaN    NaN     NaN
4  93707      10.0       2.0       1.0  ...     NaN     NaN    NaN     NaN

[5 rows x 549 columns]

In [79]:
# writing to Excel 
datatoexcel = pd.ExcelWriter('Data_final.xlsx') 
  
# write DataFrame to excel 
dd3.to_excel(datatoexcel) 
  
# save the excel 
datatoexcel.save()